# Zebrafish-optimized parameters
# Place in: conf/parameters/zebrafish.yaml

# ============================================================
# IMAGE PROCESSING
# ============================================================
patch_size: [8, 256, 256]
overlap: [1, 16, 16]
crop: [2, 32, 32]

# Tiling for large images - increase if memory errors
n_tiles: [2, 4, 4]  # [Z, Y, X] - increase for larger volumes

axes: 'ZYX'
file_type: '*.tif'

# ============================================================
# CHANNEL ASSIGNMENTS
# ============================================================
# S-BIAD499 and similar datasets:
# Channel 0 = membrane/mesoderm (drl:GFP)
# Channel 1 = nuclei (H2B-RFP)
channel_membrane: 0
channel_nuclei: 1

# ============================================================
# CELLPOSE PARAMETERS - ZEBRAFISH OPTIMIZED
# ============================================================
# CRITICAL: Zebrafish cells are SMALLER than Xenopus!
# Xenopus: ~34 px diameter
# Zebrafish gastrulation: ~12-18 px diameter

diameter_cellpose: 16.0     # Adjust based on your actual cell size!
stitch_threshold: 0.5       # For 3D stitching of 2D slices
flow_threshold: 1.0         # Default, may need tuning
cellprob_threshold: -1.0    # More negative = more permissive
anisotropy: null            # Set if z-resolution differs significantly

gpu: True
do_3D: False               # Use 2D + stitching (more reliable)
z_thresh: 2

# Cellpose model selection
cellpose_model_path: null   # null = use built-in model
# cellpose_model_type: 'cyto3'  # Good general model
# cellpose_model_type: 'nuclei'  # For nuclear segmentation

# ============================================================
# STARDIST / VOLLSEG NUCLEI PARAMETERS
# ============================================================
min_size: 30               # Minimum nucleus volume (voxels) - zebrafish nuclei smaller!
max_size: 3000             # Maximum nucleus volume (voxels)
min_size_mask: 10

prob_thresh_nuclei: null    # null = use model default
nms_thresh_nuclei: null     # null = use model default
prob_thresh_membrane: null
nms_thresh_membrane: null

UseProbability: True
ExpandLabels: False
slice_merge: False

# Normalization
donormalize: True
lower_perc: 1.0
upper_perc: 99.8

# ============================================================
# NETWORK ARCHITECTURE (if training)
# ============================================================
in_channels: 1
out_channels: 4
out_activation: 'tanh'
norm_method: 'instance'
background_weight: 1
flow_weight: 1
feat_channels: [32, 64, 128]
num_levels: 3
depth: 3
kern_size: 3
n_rays: 96               # StarDist rays
startfilter: 64

# ============================================================
# TRAINING PARAMETERS (if retraining models)
# ============================================================
batch_size: 8             # Reduce if GPU memory limited
learning_rate: 1.0e-4
epochs: 200
validation_split: 0.1
n_patches_per_image: 8

num_gpu: 1
network_type: "unet"
generate_npz: False

# ============================================================
# UNet parameters
# ============================================================
grid_x: 1
grid_y: 1
grid_z: 1
dounet: True
train_unet: True
train_star: True
train_loss: "mae"
seedpool: False
use_gpu_opencl: True
erosion_iterations: 0

# ============================================================
# DISPLAY / OUTPUT
# ============================================================
load_data_sequence: True
save_dir: null
Name: 'zebrafish_result'

# For Cellpose training
patch_x: 512
patch_y: 512
